# Before your start:
- Read the README.md file
- Comment as much as you can and use the resources (README.md file)
- Happy learning!

In [1]:
# import numpy and pandas
import numpy as np
import pandas as pd

# Challenge 1 - Exploring the Data

In this challenge, we will examine all salaries of employees of the City of Chicago. We will start by loading the dataset and examining its contents.

In [2]:
# Your code here:
chicago = pd.read_csv('Current_Employee_Names__Salaries__and_Position_Titles.csv')

Examine the `salaries` dataset using the `head` function below.

In [3]:
# Your code here:

chicago.head()

,Name,Job Titles,Department,Full or Part-Time,Salary or Hourly,Typical Hours,Annual Salary,Hourly Rate
0,"AARON, JEFFERY M",SERGEANT,POLICE,F,Salary,NaN,101442.0,NaN
1,"AARON, KARINA",POLICE OFFICER (ASSIGNED AS DETECTIVE),POLICE,F,Salary,NaN,94122.0,NaN
2,"AARON, KIMBERLEI R",CHIEF CONTRACT EXPEDITER,GENERAL SERVICES,F,Salary,NaN,101592.0,NaN
3,"ABAD JR, VICENTE M",CIVIL ENGINEER IV,WATER MGMNT,F,Salary,NaN,110064.0,NaN
4,"ABASCAL, REECE E",TRAFFIC CONTROL AIDE-HOURLY,OEMC,P,Hourly,20.0,NaN,19.86

We see from looking at the `head` function that there is quite a bit of missing data. Let's examine how much missing data is in each column. Produce this output in the cell below

In [4]:
# Your code here:

nan_counts = chicago.isnull().sum(axis = 0)
nan_counts

Name                     0
Job Titles               0
Department               0
Full or Part-Time        0
Salary or Hourly         0
Typical Hours        25161
Annual Salary         8022
Hourly Rate          25161
dtype: int64

Let's also look at the count of hourly vs. salaried employees. Write the code in the cell below

In [5]:
# Your code here:
chicago['Salary or Hourly'].value_counts()

Salary    25161
Hourly     8022
Name: Salary or Hourly, dtype: int64

What this information indicates is that the table contains information about two types of employees - salaried and hourly. Some columns apply only to one type of employee while other columns only apply to another kind. This is why there are so many missing values. Therefore, we will not do anything to handle the missing values.

There are different departments in the city. List all departments and the count of employees in each department.

In [6]:
# Your code here:

department_table1 = chicago.pivot_table(index= ['Department'],  aggfunc = {'Name':'count'})
department_table = department_table1.rename(columns={"Name": "Number of Employees"})
department_table

                       Number of Employees
Department
ADMIN HEARNG                            39
ANIMAL CONTRL                           81
AVIATION                              1629
BOARD OF ELECTION                      107
BOARD OF ETHICS                          8
BUDGET & MGMT                           46
BUILDINGS                              269
BUSINESS AFFAIRS                       171
CITY CLERK                              84
CITY COUNCIL                           411
COMMUNITY DEVELOPMENT                  207
COPA                                   116
CULTURAL AFFAIRS                        65
DISABILITIES                            28
DoIT                                    99
FAMILY & SUPPORT                       615
FINANCE                                560
FIRE                                  4641
GENERAL SERVICES                       980
HEALTH                                 488
HUMAN RELATIONS                         16
HUMAN RESOURCES                         79
INSPECTOR GEN                           87
LAW                                    407
LICENSE APPL COMM                        1
MAYOR'S OFFICE                          85
OEMC                                  2102
POLICE                               13414
POLICE BOARD                             2
PROCUREMENT                             92
PUBLIC LIBRARY                        1015
STREETS & SAN                         2198
TRANSPORTN                            1140
TREASURER                               22
WATER MGMNT                           1879

# Challenge 2 - Hypothesis Tests

In this section of the lab, we will test whether the hourly wage of all hourly workers is significantly different from $30/hr. Import the correct one sample test function from scipy and perform the hypothesis test for a 95% two sided confidence interval.

In [7]:
# Your code here:

#create list of hourly rates

hourly_list_nans = chicago['Hourly Rate'].tolist()
hourly_list_nans

[nan,
 nan,
 nan,
 nan,
 19.86,
 nan,
 46.1,
 35.6,
 nan,
 nan,
 2.65,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 17.68,
 46.1,
 nan,
 21.43,
 nan,
 nan,
 35.6,
 nan,
 25.1,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 20.0,
 nan,
 nan,
 36.21,
 nan,
 nan,
 35.6,
 45.07,
 nan,
 44.88,
 nan,
 nan,
 nan,
 nan,
 nan,
 46.1,
 nan,
 nan,
 nan,
 48.25,
 nan,
 nan,
 nan,
 36.22,
 40.2,
 nan,
 nan,
 nan,
 nan,
 36.13,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 40.2,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 32.04,
 nan,
 nan,
 28.48,
 nan,
 nan,
 nan,
 nan,
 17.68,
 47.5,
 nan,
 nan,
 46.1,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 36.21,
 nan,
 40.2,
 nan,
 nan,
 36.21,
 32.25,
 nan,
 nan,
 46.35,
 21.2,
 nan,
 nan,
 nan,
 35.6,
 nan,
 2.65,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 40.2,
 nan,
 nan,
 36.21,
 nan,
 nan,
 nan,
 nan,
 28.48,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 20.77,
 nan,
 13.15,
 nan,
 21.98,
 nan,
 nan,
 35.6,
 nan,
 nan,
 nan,
 nan,
 15.94,
 nan,
 20.12,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 40.2,
 35.6,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 40.2,
 19.86,
 nan,
 12.49,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 35.6,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 36.21,
 36.21,
 nan,
 nan,
 nan,
 nan,
 nan,
 35.6,
 36.21,
 nan,
 nan,
 35.6,
 nan,
 nan,
 32.04,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 36.21,
 nan,
 nan,
 nan,
 nan,
 35.6,
 nan,
 nan,
 36.21,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 35.6,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 34.57,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 16.17,
 nan,
 nan,
 nan,
 nan,
 13.94,
 nan,
 nan,
 nan,
 nan,
 35.6,
 35.6,
 35.6,
 8.25,
 nan,
 nan,
 nan,
 nan,
 nan,
 47.44,
 nan,
 nan,
 19.86,
 nan,
 nan,
 36.21,
 35.6,
 nan,
 nan,
 nan,
 19.86,
 nan,
 nan,
 nan,
 nan,
 nan,
 2.65,
 nan,
 nan,
 nan,
 46.35,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 35.6,
 nan,
 nan,
 32.59,
 43.03,
 36.22,
 nan,
 46.35,
 nan,
 nan,
 8.25,
 nan,
 nan,
 40.2,
 36.21,
 15.22,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 28.14,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 40.2,
 nan,
 nan,
 nan,
 nan,
 nan,
 45.07,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 19.86,
 35.6,
 40.2,
 nan,
 nan,
 nan,
 19.38,
 nan,
 nan,
 nan,
 48.25,
 nan,
 nan,
 18.52,
 36.21,
 44.25,
 2.65,
 nan,
 13.94,
 nan,
 21.3,
 nan,
 nan,
 nan,
 36.21,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 49.1,
 nan,
 18.52,
 nan,
 15.65,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 19.38,
 40.2,
 nan,
 47.44,
 nan,
 nan,
 36.21,
 nan,
 nan,
 nan,
 47.44,
 nan,
 nan,
 nan,
 40.2,
 15.0,
 nan,
 nan,
 nan,
 44.25,
 47.44,
 nan,
 nan,
 nan,
 32.04,
 nan,
 nan,
 21.98,
 nan,
 nan,
 nan,
 nan,
 nan,
 19.86,
 nan,
 nan,
 nan,
 nan,
 18.15,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 22.36,
 nan,
 36.21,
 nan,
 nan,
 nan,
 nan,
 18.52,
 25.1,
 nan,
 nan,
 nan,
 nan,
 35.6,
 46.35,
 35.6,
 35.6,
 nan,
 nan,
 35.57,
 19.86,
 nan,
 nan,
 14.54,
 35.6,
 36.21,
 nan,
 36.21,
 nan,
 nan,
 nan,
 22.12,
 36.21,
 nan,
 nan,
 nan,
 nan,
 45.07,
 nan,
 35.6,
 nan,
 nan,
 nan,
 49.1,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 35.6,
 nan,
 nan,
 nan,
 nan,
 nan,
 16.17,
 35.6,
 nan,
 nan,
 nan,
 nan,
 40.2,
 nan,
 nan,
 nan,
 nan,
 nan,
 19.86,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 50.25,
 35.6,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 36.21,
 38.33,
 36.21,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 35.6,
 nan,
 35.6,
 nan,
 nan,
 36.21,
 nan,
 32.04,
 nan,
 nan,
 nan,
 nan,
 35.6,
 35.6,
 nan,
 nan,
 36.21,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 35.6,
 35.6,
 nan,
 nan,
 nan,
 nan,
 13.0,
 nan,
 35.6,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 49.1,
 nan,
 45.07,
 nan,
 nan,
 nan,
 35.6,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 37.25,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 35.6,
 nan,
 nan,
 nan,
 nan,
 nan,
 35.6,
 36.13,
 nan,
 nan,
 35.6,
 35.6,
 nan,
 nan,
 13.15,
 13.94,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 44.88,
 nan,
 nan,
 nan,
 nan,
 20.31,
 50.25,
 nan,
 nan,
 nan,
 nan,
 19.86,
 nan,
 nan,
 nan,
 nan,
 nan,
 40.7,
 32.04,
 nan,
 52.18,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 40.2,
 nan,
 nan,
 nan,
 20.12,
 nan,
 nan,
 nan,
 47.44,
 40.2,
 nan,
 35.6,
 46.1,
 nan,
 nan,
 nan,
 nan,
 19.86,
 nan,
 nan,
 35.6,
 nan,
 nan,
 nan,
 nan,
 nan,
 2.65,
 36.21,
 nan,
 nan,
 13.94,
 14.54,
 47.44,
 36.21,
 nan,
 nan,
 40.2,
 nan,
 nan,
 nan,
 nan,
 13.94,
 nan,
 nan,
 19.38,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 35.6,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 36.21,
 nan,
 nan,
 nan,
 nan,
 40.2,
 16.17,
 35.6,
 nan,
 nan,
 41.1,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 46.1,
 nan,
 nan,
 44.55,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 21.43,
 19.5,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 40.2,
 36.21,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 19.86,
 nan,
 nan,
 nan,
 35.6,
 37.56,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 22.35,
 nan,
 nan,
 nan,
 41.7,
 nan,
 35.6,
 nan,
 52.18,
 47.44,
 nan,
 nan,
 nan,
 14.51,
 nan,
 36.21,
 37.45,
 nan,
 nan,
 nan,
 nan,
 45.07,
 36.21,
 nan,
 nan,
 35.6,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 40.2,
 12.0,
 nan,
 nan,
 35.6,
 nan,
 nan,
 35.6,
 nan,
 35.6,
 nan,
 nan,
 19.86,
 nan,
 nan,
 49.1,
 nan,
 nan,
 nan,
 40.2,
 44.55,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 40.2,
 nan,
 nan,
 nan,
 36.21,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 nan,
 36.22,
 35.6,
 nan,
 ...]

In [8]:
#clean list from nans

hourly_list = [x for x in hourly_list_nans if str(x) != 'nan']
hourly_list

[19.86,
 46.1,
 35.6,
 2.65,
 17.68,
 46.1,
 21.43,
 35.6,
 25.1,
 20.0,
 36.21,
 35.6,
 45.07,
 44.88,
 46.1,
 48.25,
 36.22,
 40.2,
 36.13,
 40.2,
 32.04,
 28.48,
 17.68,
 47.5,
 46.1,
 36.21,
 40.2,
 36.21,
 32.25,
 46.35,
 21.2,
 35.6,
 2.65,
 40.2,
 36.21,
 28.48,
 20.77,
 13.15,
 21.98,
 35.6,
 15.94,
 20.12,
 40.2,
 35.6,
 40.2,
 19.86,
 12.49,
 35.6,
 36.21,
 36.21,
 35.6,
 36.21,
 35.6,
 32.04,
 36.21,
 35.6,
 36.21,
 35.6,
 34.57,
 16.17,
 13.94,
 35.6,
 35.6,
 35.6,
 8.25,
 47.44,
 19.86,
 36.21,
 35.6,
 19.86,
 2.65,
 46.35,
 35.6,
 32.59,
 43.03,
 36.22,
 46.35,
 8.25,
 40.2,
 36.21,
 15.22,
 28.14,
 40.2,
 45.07,
 19.86,
 35.6,
 40.2,
 19.38,
 48.25,
 18.52,
 36.21,
 44.25,
 2.65,
 13.94,
 21.3,
 36.21,
 49.1,
 18.52,
 15.65,
 19.38,
 40.2,
 47.44,
 36.21,
 47.44,
 40.2,
 15.0,
 44.25,
 47.44,
 32.04,
 21.98,
 19.86,
 18.15,
 22.36,
 36.21,
 18.52,
 25.1,
 35.6,
 46.35,
 35.6,
 35.6,
 35.57,
 19.86,
 14.54,
 35.6,
 36.21,
 36.21,
 22.12,
 36.21,
 45.07,
 35.6,
 49.1,
 35.6,
 16.17,
 35.6,
 40.2,
 19.86,
 50.25,
 35.6,
 36.21,
 38.33,
 36.21,
 35.6,
 35.6,
 36.21,
 32.04,
 35.6,
 35.6,
 36.21,
 35.6,
 35.6,
 13.0,
 35.6,
 49.1,
 45.07,
 35.6,
 37.25,
 35.6,
 35.6,
 36.13,
 35.6,
 35.6,
 13.15,
 13.94,
 44.88,
 20.31,
 50.25,
 19.86,
 40.7,
 32.04,
 52.18,
 40.2,
 20.12,
 47.44,
 40.2,
 35.6,
 46.1,
 19.86,
 35.6,
 2.65,
 36.21,
 13.94,
 14.54,
 47.44,
 36.21,
 40.2,
 13.94,
 19.38,
 35.6,
 36.21,
 40.2,
 16.17,
 35.6,
 41.1,
 46.1,
 44.55,
 21.43,
 19.5,
 40.2,
 36.21,
 19.86,
 35.6,
 37.56,
 22.35,
 41.7,
 35.6,
 52.18,
 47.44,
 14.51,
 36.21,
 37.45,
 45.07,
 36.21,
 35.6,
 40.2,
 12.0,
 35.6,
 35.6,
 35.6,
 19.86,
 49.1,
 40.2,
 44.55,
 40.2,
 36.21,
 36.22,
 35.6,
 37.25,
 44.88,
 35.6,
 53.9,
 35.6,
 36.21,
 48.9,
 45.35,
 19.38,
 19.86,
 19.38,
 44.55,
 35.6,
 35.6,
 40.2,
 46.1,
 36.21,
 36.21,
 36.21,
 35.6,
 19.5,
 22.12,
 46.35,
 35.6,
 45.35,
 22.12,
 18.52,
 19.38,
 46.35,
 35.6,
 36.21,
 36.21,
 13.94,
 2.65,
 40.2,
 35.6,
 19.61,
 36.21,
 14.54,
 20.12,
 16.17,
 35.6,
 17.68,
 35.6,
 40.2,
 40.2,
 40.2,
 40.2,
 18.52,
 35.6,
 40.2,
 44.25,
 36.13,
 35.6,
 28.48,
 28.48,
 36.21,
 40.2,
 36.21,
 36.21,
 46.35,
 46.1,
 52.18,
 37.25,
 32.25,
 16.17,
 22.88,
 40.2,
 14.51,
 30.2,
 35.6,
 40.2,
 40.2,
 36.21,
 44.25,
 20.77,
 44.25,
 35.6,
 36.21,
 24.63,
 18.52,
 35.6,
 46.1,
 35.6,
 18.22,
 20.12,
 28.48,
 48.25,
 20.77,
 35.6,
 36.21,
 19.0,
 17.68,
 40.2,
 35.6,
 19.86,
 35.6,
 36.21,
 16.88,
 18.52,
 40.2,
 40.2,
 40.2,
 34.57,
 22.36,
 35.6,
 35.6,
 40.2,
 32.04,
 21.3,
 17.68,
 40.2,
 36.21,
 34.57,
 36.21,
 35.6,
 35.6,
 28.14,
 13.94,
 35.6,
 13.94,
 17.42,
 18.52,
 28.48,
 22.36,
 18.22,
 13.94,
 15.0,
 36.21,
 45.43,
 22.0,
 47.5,
 15.0,
 35.6,
 22.36,
 34.33,
 49.1,
 21.98,
 50.25,
 22.35,
 35.6,
 46.35,
 46.1,
 46.1,
 18.52,
 36.21,
 52.1,
 36.21,
 13.15,
 13.0,
 36.21,
 2.65,
 13.0,
 35.6,
 36.21,
 40.2,
 46.1,
 21.2,
 46.1,
 2.65,
 21.98,
 19.86,
 36.21,
 47.5,
 20.31,
 21.2,
 35.6,
 35.6,
 46.1,
 13.94,
 22.12,
 13.15,
 40.2,
 46.35,
 48.9,
 36.21,
 12.0,
 23.31,
 47.44,
 33.56,
 35.6,
 36.21,
 40.2,
 13.0,
 28.48,
 49.1,
 48.9,
 35.6,
 35.6,
 36.21,
 35.6,
 47.8,
 35.6,
 40.2,
 52.18,
 45.07,
 32.25,
 35.6,
 35.6,
 22.83,
 22.12,
 46.1,
 9.27,
 28.48,
 22.12,
 35.6,
 21.43,
 40.2,
 13.0,
 2.65,
 47.44,
 46.35,
 46.35,
 36.13,
 19.38,
 14.65,
 21.43,
 35.6,
 28.48,
 36.21,
 22.36,
 23.31,
 40.2,
 40.2,
 35.6,
 19.86,
 2.65,
 46.1,
 40.2,
 36.21,
 35.6,
 44.25,
 25.1,
 48.25,
 40.2,
 46.35,
 35.6,
 13.94,
 19.38,
 45.75,
 48.25,
 36.21,
 19.86,
 40.2,
 36.22,
 2.65,
 46.1,
 15.94,
 17.42,
 40.2,
 20.12,
 32.16,
 22.12,
 32.04,
 13.94,
 36.21,
 18.22,
 35.6,
 19.86,
 22.35,
 46.1,
 35.6,
 35.6,
 40.2,
 19.86,
 21.98,
 35.6,
 19.86,
 25.1,
 47.5,
 45.35,
 40.2,
 35.6,
 14.54,
 20.31,
 40.2,
 35.6,
 13.94,
 46.1,
 37.25,
 35.6,
 47.44,
 45.35,
 40.2,
 19.86,
 36.21,
 36.21,
 35.6,
 20.12,
 45.07,
 2.65,
 2.65,
 40.2,
 15.94,
 35.6,
 49.1,
 36.21,
 15.22,
 15.22,
 21.55,
 41.1,
 35.6,
 46.1,
 48.25,
 2.65,
 40.2,
 19.86,
 19.86,
 49.1,
 48.25,
 35.6,
 15.22,
 45.35,
 17.42,
 28.14,
 35.6,
 22.36,
 19.38,
 15.22,
 33.56,
 13.0,
 45.07,
 35.6,
 35.6,
 35.6,
 36.21,
 35.6,
 40.2,
 44.55,
 22.12,
 35.6,
 16.0,
 35.6,
 16.17,
 45.07,
 45.35,
 19.38,
 24.12,
 36.21,
 18.52,
 26.32,
 43.03,
 21.43,
 47.5,
 40.2,
 35.6,
 36.22,
 44.55,
 46.35,
 52.1,
 35.6,
 13.94,
 35.6,
 35.6,
 28.48,
 12.0,
 32.25,
 35.6,
 35.6,
 40.2,
 46.1,
 40.2,
 46.1,
 17.42,
 40.2,
 14.51,
 19.86,
 45.43,
 15.22,
 14.54,
 18.52,
 35.6,
 35.6,
 14.51,
 36.21,
 49.1,
 46.35,
 34.57,
 21.3,
 49.1,
 19.86,
 13.0,
 34.57,
 21.3,
 47.44,
 35.6,
 2.65,
 19.38,
 19.86,
 32.04,
 47.5,
 46.1,
 19.86,
 36.21,
 19.86,
 46.35,
 14.23,
 19.86,
 36.21,
 47.44,
 36.21,
 21.98,
 10.0,
 36.21,
 22.36,
 13.0,
 40.2,
 19.86,
 36.21,
 32.04,
 17.42,
 19.86,
 35.6,
 40.2,
 19.86,
 48.25,
 49.1,
 46.35,
 40.2,
 33.56,
 36.21,
 46.1,
 35.6,
 36.21,
 19.86,
 40.2,
 45.35,
 35.6,
 19.86,
 28.48,
 36.21,
 35.6,
 36.21,
 49.1,
 2.65,
 19.86,
 36.21,
 35.6,
 36.21,
 14.15,
 18.52,
 19.86,
 22.12,
 13.94,
 36.21,
 46.1,
 46.35,
 40.2,
 35.6,
 19.38,
 49.1,
 35.6,
 35.6,
 35.6,
 25.1,
 19.38,
 46.47,
 32.04,
 35.6,
 16.17,
 25.1,
 40.2,
 48.25,
 36.21,
 21.43,
 2.65,
 36.21,
 36.21,
 13.0,
 36.13,
 14.54,
 47.44,
 14.54,
 46.1,
 40.2,
 28.48,
 35.6,
 19.86,
 35.6,
 15.22,
 46.2,
 35.6,
 35.6,
 48.85,
 48.25,
 13.15,
 16.0,
 20.12,
 23.31,
 36.21,
 2.65,
 20.12,
 46.35,
 36.21,
 40.2,
 36.21,
 47.44,
 18.52,
 19.86,
 22.12,
 19.86,
 21.98,
 36.21,
 40.2,
 35.6,
 40.2,
 37.56,
 41.0,
 40.2,
 41.3,
 18.52,
 49.1,
 21.43,
 19.86,
 13.94,
 35.6,
 46.25,
 22.75,
 48.25,
 19.86,
 36.21,
 48.25,
 35.6,
 32.04,
 19.86,
 36.21,
 20.77,
 19.86,
 32.04,
 36.21,
 40.2,
 52.18,
 35.6,
 13.0,
 35.6,
 2.65,
 37.56,
 48.25,
 15.0,
 22.36,
 35.6,
 19.86,
 48.85,
 21.98,
 20.24,
 13.0,
 15.94,
 8.25,
 15.94,
 35.6,
 35.6,
 18.52,
 40.2,
 48.25,
 35.6,
 35.6,
 20.88,
 40.2,
 14.54,
 19.86,
 8.25,
 17.68,
 35.6,
 35.6,
 46.35,
 19.86,
 35.6,
 19.5,
 45.07,
 30.21,
 36.21,
 9.27,
 36.21,
 36.21,
 2.65,
 16.17,
 35.6,
 36.21,
 21.3,
 16.17,
 13.0,
 35.6,
 20.12,
 20.31,
 8.25,
 40.2,
 47.44,
 16.17,
 22.36,
 45.43,
 19.86,
 13.94,
 36.21,
 20.12,
 28.48,
 17.68,
 41.1,
 19.86,
 36.21,
 46.35,
 35.6,
 19.86,
 35.6,
 36.21,
 46.35,
 40.2,
 17.55,
 46.1,
 40.2,
 36.21,
 37.25,
 36.21,
 35.6,
 13.15,
 32.04,
 19.86,
 40.2,
 41.72,
 13.0,
 35.6,
 40.2,
 35.6,
 35.6,
 46.1,
 19.5,
 22.36,
 35.6,
 2.65,
 46.35,
 44.25,
 32.04,
 13.15,
 50.5,
 19.38,
 17.42,
 22.36,
 47.44,
 22.12,
 47.44,
 36.21,
 35.6,
 32.04,
 14.54,
 35.6,
 35.6,
 15.94,
 28.48,
 40.2,
 40.2,
 48.25,
 19.5,
 15.22,
 35.6,
 36.13,
 2.65,
 40.2,
 24.41,
 14.54,
 22.36,
 21.98,
 19.5,
 36.21,
 52.18,
 20.31,
 46.1,
 49.1,
 19.86,
 35.6,
 13.0,
 35.6,
 19.86,
 19.86,
 14.54,
 36.21,
 17.55,
 32.04,
 47.44,
 45.43,
 40.2,
 35.6,
 19.38,
 48.25,
 46.1,
 35.6,
 35.6,
 36.21,
 46.35,
 46.47,
 45.07,
 46.1,
 35.6,
 32.25,
 21.98,
 45.07,
 19.38,
 20.31,
 21.2,
 40.2,
 35.6,
 50.25,
 19.38,
 36.21,
 36.21,
 36.21,
 28.48,
 19.86,
 18.52,
 22.36,
 15.22,
 18.22,
 35.6,
 2.65,
 2.65,
 46.25,
 21.98,
 40.2,
 28.48,
 35.6,
 35.6,
 48.25,
 48.25,
 20.31,
 19.86,
 14.51,
 15.22,
 46.1,
 36.21,
 35.6,
 19.86,
 40.2,
 36.21,
 19.86,
 35.6,
 35.6,
 36.21,
 12.49,
 40.2,
 35.6,
 40.2,
 40.2,
 19.86,
 46.1,
 13.0,
 2.65,
 35.6,
 19.86,
 49.1,
 45.07,
 18.52,
 22.36,
 25.1,
 16.0,
 44.88,
 35.6,
 12.49,
 28.48,
 35.6,
 23.31,
 36.21,
 46.35,
 40.2,
 35.6,
 12.49,
 35.6,
 46.1,
 13.0,
 21.98,
 45.07,
 48.25,
 22.35,
 46.35,
 40.2,
 47.44,
 46.1,
 ...]

In [9]:
# H0 : hourly rate mean = 30

#confidence_level = 0.95
#significance_level = 1 - 0.95 = 0.05 
#for a two sided sided confidence interval we will compare to 0.05/2 = 0.025


from scipy import stats

test = stats.ttest_1samp(hourly_list, 30)
test

#here we can see that the p-value is much smaller than the significance level which indicates we should reject the H0

Ttest_1sampResult(statistic=20.6198057854942, pvalue=4.3230240486229894e-92)

We are also curious about salaries in the police force. The chief of police in Chicago claimed in a press briefing that salaries this year are higher than last year's mean of $86000/year a year for all salaried employees. Test this one sided hypothesis using a 95% confidence interval.

Hint: A one tailed test has a p-value that is half of the two tailed p-value. If our hypothesis is greater than, then to reject, the test statistic must also be positive.

In [10]:
# Your code here:

#get a list of all Police Salaries

police_frame = chicago[(chicago['Salary or Hourly'] == 'Salary') & (chicago['Department'] == 'POLICE')]
police_list = police_frame['Annual Salary'].tolist()
police_list

[101442.0,
 94122.0,
 93354.0,
 84054.0,
 87006.0,
 84054.0,
 90024.0,
 48078.0,
 76266.0,
 48078.0,
 80016.0,
 72510.0,
 68616.0,
 90024.0,
 48078.0,
 76266.0,
 48078.0,
 72510.0,
 97440.0,
 72510.0,
 87006.0,
 90024.0,
 84054.0,
 87006.0,
 90024.0,
 72510.0,
 87006.0,
 43800.0,
 76266.0,
 84054.0,
 84054.0,
 90024.0,
 100980.0,
 90024.0,
 90024.0,
 90024.0,
 87006.0,
 93354.0,
 93354.0,
 72510.0,
 93354.0,
 50676.0,
 87006.0,
 72510.0,
 90024.0,
 72510.0,
 84054.0,
 94524.0,
 48078.0,
 90024.0,
 100980.0,
 96060.0,
 100776.0,
 87006.0,
 40392.0,
 48078.0,
 68616.0,
 100980.0,
 93354.0,
 48078.0,
 48078.0,
 84054.0,
 76266.0,
 84054.0,
 97440.0,
 90024.0,
 94524.0,
 84054.0,
 111474.0,
 90024.0,
 50676.0,
 96060.0,
 91338.0,
 96060.0,
 111474.0,
 93354.0,
 87006.0,
 96060.0,
 103932.0,
 94524.0,
 111474.0,
 87006.0,
 84054.0,
 84054.0,
 104628.0,
 90024.0,
 48078.0,
 87006.0,
 76266.0,
 90024.0,
 80016.0,
 88296.0,
 96060.0,
 87006.0,
 90024.0,
 84054.0,
 84054.0,
 103932.0,
 100980.0,
 91338.0,
 101442.0,
 96060.0,
 48078.0,
 93354.0,
 93354.0,
 72510.0,
 87006.0,
 48078.0,
 72510.0,
 72510.0,
 88344.0,
 48078.0,
 90024.0,
 93354.0,
 53076.0,
 90024.0,
 80016.0,
 48078.0,
 100980.0,
 68616.0,
 93354.0,
 94122.0,
 96060.0,
 90024.0,
 87006.0,
 91338.0,
 93354.0,
 84054.0,
 93354.0,
 93354.0,
 100980.0,
 90024.0,
 84054.0,
 90024.0,
 87006.0,
 87006.0,
 48078.0,
 76266.0,
 96060.0,
 84054.0,
 72510.0,
 91338.0,
 87006.0,
 48078.0,
 72510.0,
 87006.0,
 87006.0,
 90024.0,
 87006.0,
 90024.0,
 120252.0,
 107988.0,
 90024.0,
 84054.0,
 76266.0,
 93354.0,
 70092.0,
 48078.0,
 91338.0,
 127692.0,
 170112.0,
 87006.0,
 93354.0,
 70644.0,
 90024.0,
 96060.0,
 87006.0,
 87006.0,
 93354.0,
 84054.0,
 93354.0,
 87006.0,
 90024.0,
 103932.0,
 93354.0,
 90024.0,
 87006.0,
 48078.0,
 93354.0,
 48078.0,
 87006.0,
 102672.0,
 87006.0,
 107988.0,
 72510.0,
 68616.0,
 66948.0,
 111252.0,
 107988.0,
 94524.0,
 76266.0,
 40392.0,
 96060.0,
 93354.0,
 104628.0,
 101442.0,
 111474.0,
 103932.0,
 96060.0,
 48078.0,
 90024.0,
 96060.0,
 87006.0,
 84054.0,
 100980.0,
 72510.0,
 76266.0,
 87006.0,
 90024.0,
 43800.0,
 93354.0,
 90024.0,
 93354.0,
 76266.0,
 84054.0,
 104628.0,
 90024.0,
 91080.0,
 100980.0,
 48078.0,
 48078.0,
 90024.0,
 111474.0,
 87006.0,
 97440.0,
 101442.0,
 76266.0,
 87006.0,
 84054.0,
 84054.0,
 48078.0,
 72510.0,
 48078.0,
 87006.0,
 90024.0,
 70092.0,
 48078.0,
 87006.0,
 72510.0,
 104628.0,
 90024.0,
 93354.0,
 91338.0,
 87006.0,
 48078.0,
 48078.0,
 104628.0,
 87006.0,
 80016.0,
 84054.0,
 68616.0,
 48078.0,
 100980.0,
 84054.0,
 80016.0,
 104628.0,
 76266.0,
 94524.0,
 76266.0,
 84054.0,
 84054.0,
 72510.0,
 111474.0,
 84054.0,
 104628.0,
 111474.0,
 91338.0,
 48078.0,
 76266.0,
 48078.0,
 48078.0,
 48078.0,
 72510.0,
 76266.0,
 93354.0,
 111192.0,
 93354.0,
 98052.0,
 127692.0,
 97440.0,
 103932.0,
 94122.0,
 103932.0,
 48078.0,
 90024.0,
 87006.0,
 104628.0,
 76266.0,
 90024.0,
 93354.0,
 48078.0,
 90024.0,
 67464.0,
 84054.0,
 91338.0,
 111492.0,
 68616.0,
 84054.0,
 48078.0,
 72510.0,
 84054.0,
 87006.0,
 107988.0,
 98052.0,
 87006.0,
 94122.0,
 127692.0,
 48078.0,
 48078.0,
 84054.0,
 100980.0,
 90024.0,
 90024.0,
 84054.0,
 87006.0,
 90024.0,
 93354.0,
 87006.0,
 87006.0,
 103932.0,
 72510.0,
 96060.0,
 48078.0,
 136170.0,
 93354.0,
 93354.0,
 48078.0,
 104628.0,
 84054.0,
 96060.0,
 104628.0,
 98052.0,
 104628.0,
 93354.0,
 48078.0,
 93354.0,
 96060.0,
 90024.0,
 97440.0,
 90024.0,
 87006.0,
 48078.0,
 96060.0,
 48078.0,
 72510.0,
 103932.0,
 93354.0,
 111474.0,
 84054.0,
 84054.0,
 84054.0,
 93354.0,
 48078.0,
 87006.0,
 87006.0,
 90024.0,
 94524.0,
 76266.0,
 48078.0,
 94122.0,
 93354.0,
 80016.0,
 48078.0,
 93300.0,
 93354.0,
 48078.0,
 72510.0,
 76266.0,
 93354.0,
 90024.0,
 96060.0,
 84054.0,
 40392.0,
 107988.0,
 87006.0,
 84054.0,
 87006.0,
 90024.0,
 87006.0,
 48078.0,
 84054.0,
 87006.0,
 72510.0,
 70092.0,
 84054.0,
 84054.0,
 107988.0,
 48078.0,
 48078.0,
 84054.0,
 48078.0,
 87006.0,
 72510.0,
 84054.0,
 87006.0,
 84054.0,
 90024.0,
 90024.0,
 93354.0,
 72510.0,
 90024.0,
 87006.0,
 72510.0,
 84054.0,
 90024.0,
 87006.0,
 90024.0,
 84054.0,
 48078.0,
 101592.0,
 87006.0,
 87006.0,
 84054.0,
 88296.0,
 90024.0,
 48072.0,
 87006.0,
 87006.0,
 129096.0,
 87006.0,
 90024.0,
 96060.0,
 68616.0,
 103932.0,
 90024.0,
 93354.0,
 48078.0,
 93354.0,
 93354.0,
 76266.0,
 87006.0,
 48078.0,
 84054.0,
 40392.0,
 48078.0,
 80016.0,
 84054.0,
 93354.0,
 48078.0,
 87006.0,
 96060.0,
 87006.0,
 48078.0,
 73440.0,
 87006.0,
 90024.0,
 90024.0,
 68616.0,
 48078.0,
 127692.0,
 103932.0,
 104628.0,
 96060.0,
 107988.0,
 68616.0,
 84054.0,
 72510.0,
 91338.0,
 84054.0,
 61464.0,
 67464.0,
 94122.0,
 93354.0,
 72510.0,
 87006.0,
 84054.0,
 93354.0,
 90024.0,
 111474.0,
 87006.0,
 76266.0,
 84054.0,
 90024.0,
 67464.0,
 93354.0,
 48078.0,
 56568.0,
 94122.0,
 90024.0,
 104628.0,
 101442.0,
 100980.0,
 48078.0,
 93354.0,
 93354.0,
 70092.0,
 93354.0,
 93354.0,
 87006.0,
 93354.0,
 87006.0,
 48078.0,
 90024.0,
 91338.0,
 111474.0,
 48078.0,
 87006.0,
 87006.0,
 94524.0,
 162684.0,
 48078.0,
 88296.0,
 84054.0,
 76266.0,
 97440.0,
 68616.0,
 68616.0,
 107988.0,
 91338.0,
 48078.0,
 84054.0,
 84054.0,
 48078.0,
 104628.0,
 104628.0,
 76266.0,
 90024.0,
 90024.0,
 87006.0,
 48078.0,
 87006.0,
 94122.0,
 94122.0,
 72510.0,
 93354.0,
 48078.0,
 104628.0,
 93354.0,
 48078.0,
 93354.0,
 76266.0,
 100980.0,
 93354.0,
 90024.0,
 96060.0,
 93354.0,
 90024.0,
 87006.0,
 87006.0,
 90024.0,
 48078.0,
 77520.0,
 48078.0,
 96060.0,
 48078.0,
 103932.0,
 80016.0,
 96060.0,
 87006.0,
 68616.0,
 84054.0,
 87006.0,
 136170.0,
 72510.0,
 120252.0,
 40392.0,
 80016.0,
 93354.0,
 84054.0,
 98052.0,
 93354.0,
 68616.0,
 87006.0,
 96060.0,
 87006.0,
 107988.0,
 127692.0,
 96060.0,
 58248.0,
 84054.0,
 87006.0,
 87006.0,
 93354.0,
 97440.0,
 84054.0,
 90024.0,
 87006.0,
 48078.0,
 90024.0,
 84054.0,
 93354.0,
 90024.0,
 96060.0,
 104628.0,
 91080.0,
 94524.0,
 87006.0,
 103932.0,
 96060.0,
 93354.0,
 40392.0,
 46152.0,
 87006.0,
 120252.0,
 76266.0,
 80016.0,
 76266.0,
 84054.0,
 48078.0,
 103932.0,
 90024.0,
 76266.0,
 100980.0,
 107988.0,
 84054.0,
 48078.0,
 93354.0,
 90024.0,
 84054.0,
 87006.0,
 87006.0,
 111474.0,
 87006.0,
 90024.0,
 94524.0,
 96060.0,
 96060.0,
 104628.0,
 87006.0,
 72510.0,
 94524.0,
 84054.0,
 84054.0,
 48078.0,
 76266.0,
 76266.0,
 76266.0,
 84054.0,
 107988.0,
 90024.0,
 90024.0,
 48078.0,
 87006.0,
 96060.0,
 84054.0,
 107988.0,
 87006.0,
 93354.0,
 93354.0,
 93354.0,
 93354.0,
 58248.0,
 100980.0,
 90024.0,
 48078.0,
 87006.0,
 103932.0,
 111474.0,
 104628.0,
 96060.0,
 96060.0,
 97440.0,
 90024.0,
 93354.0,
 90024.0,
 93354.0,
 90024.0,
 101442.0,
 87006.0,
 87006.0,
 84054.0,
 127692.0,
 111474.0,
 56004.0,
 93354.0,
 90024.0,
 90024.0,
 104628.0,
 107988.0,
 90024.0,
 84054.0,
 97440.0,
 48078.0,
 90024.0,
 48078.0,
 84054.0,
 90024.0,
 72510.0,
 101442.0,
 94122.0,
 72510.0,
 87006.0,
 72510.0,
 93354.0,
 100980.0,
 90024.0,
 100980.0,
 87006.0,
 96060.0,
 87006.0,
 40392.0,
 111474.0,
 100980.0,
 73992.0,
 87006.0,
 40392.0,
 104628.0,
 90024.0,
 93354.0,
 100980.0,
 104628.0,
 87006.0,
 72510.0,
 76266.0,
 111474.0,
 87006.0,
 90024.0,
 48078.0,
 123894.0,
 87006.0,
 48078.0,
 90024.0,
 104628.0,
 84054.0,
 123894.0,
 87006.0,
 52176.0,
 84054.0,
 90024.0,
 90024.0,
 96060.0,
 87006.0,
 93354.0,
 93354.0,
 107988.0,
 98052.0,
 97440.0,
 84054.0,
 90024.0,
 162684.0,
 90024.0,
 93354.0,
 90024.0,
 84054.0,
 90024.0,
 48078.0,
 68616.0,
 104628.0,
 68616.0,
 87006.0,
 104628.0,
 90024.0,
 84054.0,
 90024.0,
 72510.0,
 170112.0,
 90024.0,
 111474.0,
 93354.0,
 48078.0,
 90024.0,
 98052.0,
 90024.0,
 87006.0,
 48078.0,
 90024.0,
 84054.0,
 93354.0,
 93354.0,
 93354.0,
 90024.0,
 90024.0,
 100980.0,
 123894.0,
 48078.0,
 84054.0,
 84054.0,
 93354.0,
 107988.0,
 72510.0,
 90024.0,
 100980.0,
 100980.0,
 104628.0,
 87006.0,
 90024.0,
 111474.0,
 103932.0,
 84054.0,
 93354.0,
 84054.0,
 84054.0,
 111474.0,
 93354.0,
 90024.0,
 97440.0,
 93354.0,
 84054.0,
 111474.0,
 96060.0,
 100980.0,
 90024.0,
 87006.0,
 48078.0,
 48078.0,
 87006.0,
 87006.0,
 87006.0,
 90024.0,
 104628.0,
 56004.0,
 100980.0,
 90024.0,
 90024.0,
 93354.0,
 96060.0,
 93354.0,
 90024.0,
 93354.0,
 90024.0,
 98052.0,
 84054.0,
 90024.0,
 48078.0,
 107988.0,
 87006.0,
 87006.0,
 90024.0,
 87006.0,
 87006.0,
 96060.0,
 80016.0,
 90024.0,
 76266.0,
 120252.0,
 97440.0,
 104628.0,
 68616.0,
 90024.0,
 84054.0,
 48078.0,
 76266.0,
 120252.0,
 90024.0,
 76266.0,
 90024.0,
 90024.0,
 77520.0,
 48078.0,
 48078.0,
 93354.0,
 91338.0,
 98052.0,
 76266.0,
 90024.0,
 93354.0,
 94122.0,
 97440.0,
 87006.0,
 48078.0,
 87006.0,
 93354.0,
 72510.0,
 93354.0,
 104628.0,
 104628.0,
 87006.0,
 76266.0,
 84054.0,
 72510.0,
 87006.0,
 93354.0,
 68616.0,
 90024.0,
 98052.0,
 111474.0,
 93354.0,
 100980.0,
 48078.0,
 87006.0,
 90024.0,
 48078.0,
 90024.0,
 50676.0,
 93354.0,
 96060.0,
 87006.0,
 87006.0,
 127692.0,
 84054.0,
 93354.0,
 87006.0,
 90024.0,
 107988.0,
 90024.0,
 107988.0,
 104628.0,
 170112.0,
 87006.0,
 68616.0,
 93354.0,
 87006.0,
 76266.0,
 90024.0,
 76266.0,
 94524.0,
 72510.0,
 84054.0,
 40392.0,
 87006.0,
 87006.0,
 127692.0,
 90024.0,
 48078.0,
 48078.0,
 87006.0,
 120252.0,
 96060.0,
 76266.0,
 48078.0,
 96060.0,
 90024.0,
 104628.0,
 127692.0,
 63876.0,
 96060.0,
 123894.0,
 111474.0,
 91338.0,
 84054.0,
 96060.0,
 111474.0,
 90024.0,
 84054.0,
 48078.0,
 93354.0,
 76266.0,
 97440.0,
 90024.0,
 84054.0,
 93354.0,
 84054.0,
 48078.0,
 93354.0,
 123894.0,
 84054.0,
 96060.0,
 96060.0,
 72510.0,
 48078.0,
 93354.0,
 100980.0,
 93354.0,
 90024.0,
 84054.0,
 76266.0,
 88296.0,
 94122.0,
 87006.0,
 87006.0,
 90024.0,
 100980.0,
 48078.0,
 90024.0,
 107988.0,
 87006.0,
 87006.0,
 93354.0,
 72510.0,
 93354.0,
 68616.0,
 68616.0,
 103932.0,
 87006.0,
 90024.0,
 90024.0,
 104628.0,
 96060.0,
 94122.0,
 103932.0,
 48078.0,
 84054.0,
 87006.0,
 88296.0,
 48078.0,
 87006.0,
 84054.0,
 93354.0,
 100980.0,
 48078.0,
 120252.0,
 94122.0,
 68616.0,
 90024.0,
 90024.0,
 111474.0,
 111474.0,
 90024.0,
 90024.0,
 96060.0,
 107988.0,
 111474.0,
 68616.0,
 90024.0,
 84054.0,
 87006.0,
 48078.0,
 48078.0,
 87006.0,
 84054.0,
 ...]

In [11]:
# H0 : mean_police_salaries > 86000
test2 = stats.ttest_1samp(police_list, 86000)
test2

#confidence_level = 0.95
#significance_level = 1 - 0.95 = 0.05 
#for a two sided sided confidence interval we will compare to 0.05/2 = 0.025

#"If our hypothesis is greater than, then to reject, the test statistic must also be positive."

#statistic is positive but p-value < 0.025 so we reject H0

Ttest_1sampResult(statistic=3.081997005712994, pvalue=0.0020603403550965137)

Using the `crosstab` function, find the department that has the most hourly workers.

In [12]:
# Your code here:

#read about 'crosstab': https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.crosstab.html

dep_most_hourly =pd.crosstab(chicago['Department'], chicago['Salary or Hourly']).sort_values(by='Hourly', ascending= False)
dep_most_hourly

Salary or Hourly       Hourly  Salary
Department
STREETS & SAN            1862     336
WATER MGMNT              1513     366
OEMC                     1273     829
AVIATION                 1082     547
GENERAL SERVICES          765     215
TRANSPORTN                725     415
PUBLIC LIBRARY            299     716
FAMILY & SUPPORT          287     328
CITY COUNCIL               64     347
FINANCE                    44     516
LAW                        40     367
ANIMAL CONTRL              19      62
POLICE                     10   13404
MAYOR'S OFFICE              8      77
BUSINESS AFFAIRS            7     164
CULTURAL AFFAIRS            7      58
COMMUNITY DEVELOPMENT       4     203
HUMAN RESOURCES             4      75
HEALTH                      3     485
PROCUREMENT                 2      90
FIRE                        2    4639
BUDGET & MGMT               2      44
HUMAN RELATIONS             0      16
INSPECTOR GEN               0      87
DoIT                        0      99
LICENSE APPL COMM           0       1
DISABILITIES                0      28
COPA                        0     116
CITY CLERK                  0      84
POLICE BOARD                0       2
BUILDINGS                   0     269
BOARD OF ETHICS             0       8
BOARD OF ELECTION           0     107
TREASURER                   0      22
ADMIN HEARNG                0      39

In [13]:
department = dep_most_hourly.loc[dep_most_hourly['Hourly'].idxmax()]
department

Salary or Hourly
Hourly    1862
Salary     336
Name: STREETS & SAN, dtype: int64

The workers from the department with the most hourly workers have complained that their hourly wage is less than $35/hour. Using a one sample t-test, test this one-sided hypothesis at the 95% confidence level.

In [14]:
# Your code here:

street_sanitation_frame = chicago[(chicago['Salary or Hourly'] == 'Hourly') & (chicago['Department'] == 'STREETS & SAN')]
street_sanitation_list = street_sanitation_frame['Hourly Rate'].tolist()
# H0 : mean < 35

# t student distribution
# one sided -> 0.5
alpha = 0.5
test3 = stats.ttest_1samp(street_sanitation_list, 35)

if test3[1] < alpha :
    print('We reject the null hypothesis with a p-value of',test3[1])
else :
    print('We accept the null hypothesis with a p-value of',test3[1])

We reject the null hypothesis with a p-value of 3.3378530564707717e-21

# Challenge 3: To practice - Constructing Confidence Intervals

While testing our hypothesis is a great way to gather empirical evidence for accepting or rejecting the hypothesis, another way to gather evidence is by creating a confidence interval. A confidence interval gives us information about the true mean of the population. So for a 95% confidence interval, we are 95% sure that the mean of the population is within the confidence interval. 
).

To read more about confidence intervals, click [here](https://en.wikipedia.org/wiki/Confidence_interval).


In the cell below, we will construct a 95% confidence interval for the mean hourly wage of all hourly workers. 

The confidence interval is computed in SciPy using the `t.interval` function. You can read more about this function [here](https://docs.scipy.org/doc/scipy-0.14.0/reference/generated/scipy.stats.t.html).

To compute the confidence interval of the hourly wage, use the 0.95 for the confidence level, number of rows - 1 for degrees of freedom, the mean of the sample for the location parameter and the standard error for the scale. The standard error can be computed using [this](https://docs.scipy.org/doc/scipy/reference/generated/scipy.stats.sem.html) function in SciPy.

In [19]:
from scipy.stats import t

# number of rows - 1 for degrees of freedom
dfreedom = len(hourly_list)-1

# mean of the sample for the location parameter
location = np.mean(hourly_list)

# the standard error for the scale
n = len(hourly_list)
scale = np.std(hourly_list) / np.sqrt(n)

In [21]:
tstudent = t(dfreedom,location,scale)

confidence_interval = tstudent.interval(0.95)

print("The confidence interval for the hourly wage with a 0.95 confidence interval is", confidence_interval)

The confidence interval for the hourly wage with a 0.95 confidence interval is (32.52347486867093, 33.053640563889545)

Now construct the 95% confidence interval for all salaried employeed in the police in the cell below.

In [23]:
# number of rows - 1 for degrees of freedom
dfreedom2 = len(police_list)-1

# mean of the sample for the location parameter
location2 = np.mean(police_list)

# the standard error for the scale
n2 = len(police_list)
scale2 = np.std(police_list) / np.sqrt(n2)

tstudent2 = t(dfreedom2,location2,scale2)

confidence_interval2 = tstudent2.interval(0.95)

print("The confidence interval for the hourly wage with a 0.95 confidence interval is", confidence_interval2)

The confidence interval for the hourly wage with a 0.95 confidence interval is (86177.06785530433, 86795.76115096245)

# Bonus Challenge - Hypothesis Tests of Proportions

Another type of one sample test is a hypothesis test of proportions. In this test, we examine whether the proportion of a group in our sample is significantly different than a fraction. 

You can read more about one sample proportion tests [here](http://sphweb.bumc.bu.edu/otlt/MPH-Modules/BS/SAS/SAS6-CategoricalData/SAS6-CategoricalData2.html).

In the cell below, use the `proportions_ztest` function from `statsmodels` to perform a hypothesis test that will determine whether the number of hourly workers in the City of Chicago is significantly different from 25% at the 95% confidence level.

In [ ]:
# Your code here: